language: php
sudo: false
php:
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
  - "$HOME/.composer/cache"
before_script:
  - travis_retry composer self-update
install:
  - travis_retry composer install --prefer-dist --no-interaction
script:
  - composer phpcs
  - composer phpunit
after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/clover.xml
matrix:
  fast_finish: true
